{
  "name": "homeBluetoothFind",
  "type": "appControl",
  "category": "utility",
  "desc": "Find a device in scanned device list using name to connect",
  "params": {
    "device": {
      "type": "string",
      "desc": "the name of the device",
      "isRequired": true
    }
  },
  "requiredPrivileges": [],
  "returns": {},
  "details": {
    "appid": "org.tizen.homescreen"
  }
}