{
  "name": "homeWifiFind",
  "type": "appControl",
  "category": "utility",
  "desc": "Find AP in scanned ap list using name to connect",
  "params": {
    "ap": {
      "type": "string",
      "desc": "the name of AP",
      "isRequired": true
    }
  },
  "requiredPrivileges": [],
  "returns": {},
  "details": {
    "appid": "org.tizen.homescreen"
  }
}