import 'dart:io';
import 'dart:convert';

const String kInputArbFile = 'lib/l10n/app_en.arb';
const String kOutputDartFile = 'lib/generated/localization_map_helper.g.dart';

void main() {
  print('--- Localization Map Generation Started ---');

  final File arbFile = File(kInputArbFile);
  if (!arbFile.existsSync()) {
    print('Error: ARB file not found at $kInputArbFile');
    exit(1);
  }

  final String content = arbFile.readAsStringSync();
  final Map<String, dynamic> jsonMap = json.decode(content);

  final List<String> keys =
      jsonMap.keys.where((key) => !key.startsWith('@')).toList();

  final StringBuffer buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// ******************************************************');
  buffer.writeln('// Generated by $kOutputDartFile script from ARB file.');
  buffer.writeln('// ******************************************************');
  buffer.writeln('');
  buffer.writeln("import 'package:flutter/material.dart';");
  buffer.writeln("import 'package:tizen_fs/l10n/app_localizations.dart';");
  buffer.writeln('');

  buffer.writeln(
    'final Map<String, String Function(AppLocalizations)> _localizationMap = {',
  );

  for (final key in keys) {
    buffer.writeln("  '$key': (loc) => loc.$key,");
  }

  buffer.writeln('};');
  buffer.writeln('');

  buffer.writeln(
    'String getLocalizedTextByKey(BuildContext context, String key) {',
  );
  buffer.writeln('  if (key.isEmpty) return key;');
  buffer.writeln('  ');
  buffer.writeln('  final loc = AppLocalizations.of(context);');
  buffer.writeln('  final getter = _localizationMap[key];');
  buffer.writeln('  ');
  buffer.writeln('  if (getter != null) {');
  buffer.writeln('    return getter(loc);');
  buffer.writeln('  }');
  buffer.writeln('  return key;');
  buffer.writeln('}');

  final File output = File(kOutputDartFile);
  if (!output.parent.existsSync()) {
    output.parent.createSync(recursive: true);
  }
  output.writeAsStringSync(buffer.toString());

  print(
    'Successfully generated map file at $kOutputDartFile (Keys: ${keys.length})',
  );
}
