{
  "name": "homeBluetoothConnect",
  "type": "appControl",
  "category": "utility",
  "desc": "Make Connection of Bluetooth to specific device.\n   - Condition: This action is available ONLY when Bluetooth is already activated.\n   - Parameters:\n     - \"device\" (string, required): \"the name of the device\".",
  "params": {
    "ap": {
      "type": "string",
      "desc": "the name of the device",
      "isRequired": true
    }
  },
  "requiredPrivileges": [],
  "returns": {},
  "details": {
    "appid": "org.tizen.homescreen"
  }
}