{
  "name": "homeLive",
  "type": "appControl",
  "category": "utility",
  "desc": "An action for playing live streaming\n   - Condition: This action is triggered when the user's request falls into the following categories:\n     - Child-Oriented Content Requests: When the user asks to play or show something specifically for a child (e.g., 'Play something for my kid,' 'Find a show for the baby').\n     - Boredom or Entertainment Needs: When the user expresses boredom or a general desire for entertainment (e.g., 'I'm bored,' 'Show me something interesting,' 'Give me some entertainment').\n   - Parameters:\n     - \"url\" (string, required): \"kids\", \"entertainment\".",
  "params": {
    "url": {
      "type": "string",
      "desc": "An url of the live",
      "isRequired": true
    }
  },
  "requiredPrivileges": [],
  "returns": {},
  "details": {
    "appid": "org.tizen.homescreen"
  }
}