{
  "name": "homeWifiConnect",
  "type": "appControl",
  "category": "utility",
  "desc": "Make Connection of Wi-Fi network to specific AP.\n   - Condition: This action is available ONLY when Wi-Fi is already activated.\n   - Parameters:\n     - \"ap\" (string, required): \"the name of AP\".",
  "params": {
    "ap": {
      "type": "string",
      "desc": "the name of AP",
      "isRequired": true
    }
  },
  "requiredPrivileges": [],
  "returns": {},
  "details": {
    "appid": "org.tizen.homescreen"
  }
}