{
  "name": "homeWifi",
  "type": "appControl",
  "category": "utility",
  "desc": "Turn on/off Wi-Fi.\n   - Parameters:\n     - \"command\" (string, required): \"on\", \"off\".\n\n",
  "params": {
    "command": {
      "type": "string",
      "desc": "A command for wifi on/off",
      "isRequired": true
    }
  },
  "requiredPrivileges": [],
  "returns": {},
  "details": {
    "appid": "org.tizen.homescreen"
  }
}